server:
  port: 9090

spring:

  datasource:
    url: jdbc:h2:mem:wastemadb
    username: sa
    password: test123
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://naming-microservice:8761/eureka